# Photon Subtraction in Graph State
2026\. 05\. 19.  Make the pseudo code

##### Basic modules, parameters and functions

###### to be continued..

## 1. Set the graph state

##### Initial parameters and modules

In [ ]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
# Graph: paper-style 6-node graph, labels 1-6 1-2-(3,4)-5-6 graph
Adj = np.array([[0, 1, 0, 0, 0, 0],
                [1, 0, 1, 1, 0, 0],
                [0, 1, 0, 0, 1, 0],
                [0, 1, 0, 0, 1, 0],
                [0, 0, 1, 1, 0, 1],
                [0, 0, 0, 0, 1, 0]], dtype=float)
m = Adj.shape[0]

# Phase-space convention: q = (x1, ..., xm, p1, ..., pm)
I_m = np.eye(m)
Z_m = np.zeros((m, m))
Omega = np.block([[Z_m, I_m], [-I_m, Z_m]]) # [0, I; -I, 0] symplectic form
J = Omega.T # [0, -I; I, 0] symplectic form in Mattia's convention

# CZ symplectic matrix
G = np.block([[I_m, Z_m], [Adj, I_m]])

# Input covariance, paper convention: vacuum variance = 1
squeezing_db = np.full(m, 10, dtype=float) # 단위는 dB 
#squeezing_db = np.array([3, 4, 12, 5, 3, 5], dtype=float) # mode별로 squeezing 다르게 주는 경우

s = 10 ** (squeezing_db / 10) # 단위 변환
V0 = np.diag(np.concatenate([s, 1 / s])) # diag(s_1, ..., s_m, 1/s_1, ..., 1/s_m)


# Graph-state covariance
V = G @ V0 @ G.T # maybe later we adjust this code to general mixed case.

# Photon-subtraction mode
f_sub = np.array([1, 0, 0, 0, 0, 0], dtype=complex) # a(f_sub) = sum f_sub[i] a_i
f_sub = f_sub / np.linalg.norm(f_sub) # 정규화
g_sub = np.concatenate([np.real(f_sub), -np.imag(f_sub)]) # g_sub = (Re(f_sub), -Im(f_sub)) in phase space , a(f_sub) = Q(g_sub)+iQ(Jg_sub) 
Jg_sub = J @ g_sub
Pi_g = np.outer(g_sub, g_sub) + np.outer(Jg_sub, Jg_sub) # Πg =ggT + Jg(Jg)T , projection matrix for the subtracted mode

sub_label = "single mode 1" # just label for the plot later

##### Graph-State Sanity

In [3]:
print("m =", m)

print("Adj =\n", Adj)
print("V =\n", V)

print("f_sub =", f_sub)
print("f_sub shape =", f_sub.shape)

eigvals_physical = np.linalg.eigvalsh(V + 1j * Omega)
print("physical covariance(V + iOmega):", np.min(eigvals_physical) >= -1e-10)
#print("min eigenvalue of V + iOmega =", np.min(eigvals_physical))

m = 6
Adj =
 [[0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0.]]
V =
 [[10.   0.   0.   0.   0.   0.   0.  10.   0.   0.   0.   0. ]
 [ 0.  10.   0.   0.   0.   0.  10.   0.  10.  10.   0.   0. ]
 [ 0.   0.  10.   0.   0.   0.   0.  10.   0.   0.  10.   0. ]
 [ 0.   0.   0.  10.   0.   0.   0.  10.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.  10.   0.   0.   0.  10.  10.   0.  10. ]
 [ 0.   0.   0.   0.   0.  10.   0.   0.   0.   0.  10.   0. ]
 [ 0.  10.   0.   0.   0.   0.  10.1  0.  10.  10.   0.   0. ]
 [10.   0.  10.  10.   0.   0.   0.  30.1  0.   0.  20.   0. ]
 [ 0.  10.   0.   0.  10.   0.  10.   0.  20.1 20.   0.  10. ]
 [ 0.  10.   0.   0.  10.   0.  10.   0.  20.  20.1  0.  10. ]
 [ 0.   0.  10.  10.   0.  10.   0.  20.   0.   0.  30.1  0. ]
 [ 0.   0.   0.   0.  10.   0.   0.   0.  10.  10.   0.  10.1]]
f_sub = [1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
f_sub shape = (6,)
physical covariance(V + iOm